server.port=8080
domainUrl=localhost
spring.application.name=PAI_DEMO
# mysql setting
spring.datasource.url=jdbc:mysql://${domainUrl}:3307/pai_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.username=root
spring.datasource.password=Yez3.1415926
# mongodb setting
spring.data.mongodb.uri=mongodb://root:Yez3.1415926@${domainUrl}:27017/pai_demo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:META-INF/mybatis/*.xml
# pagehelper
pagehelper.helperDialect=mysql
pagehelper.reasonable=false
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql
# redis
spring.redis.host=${domainUrl}
spring.redis.port=6379
spring.redis.password=Yez3.1415926
spring.redis.jedis.pool.max-active=50
spring.redis.jedis.pool.max-wait=-1
spring.redis.jedis.pool.max-idle=300
spring.redis.jedis.pool.min-idle=10
spring.redis.timeout=100000
spring.mvc.servlet.load-on-startup=1
# jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
# jpa
# ?????????? update??????? none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect